# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
warnings_are_errors: true
script:
  - R CMD build .
  - R CMD check *tar.gz --as-cran

jobs:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode12.5

apt_packages:
  - gdal-bin
  - libgdal-dev
  - libxml2-dev
  - libproj-dev
  - libudunits2-dev
  - libgeos-dev
  - libfontconfig1-dev
  - libv8-dev
  - libcairo2-dev
  - libnetcdf-dev

addons:
  homebrew:
    packages:
    - pkg-config
    - gdal

r_packages:
  - units
