# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required

install:
- R -e 'install_github("r-spatial/sf", configure.args = "--with-proj-lib=/usr/local/lib/")'

r_packages:
  - sf
