# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required

apt_packages:
    - gdal-bin
    - libgdal-dev
    - libxml2-dev
    - libproj-dev
    - libudunits2-dev
    - libgeos-dev
    - libfontconfig1-dev
    - libv8-dev
    - libcairo2-dev
    - libnetcdf-dev

r_packages:
  - units
