# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required

before_install:
  - brew install pkg-config; fi;
  - brew install gdal; fi;
  - Rscript -e "install.packages('sf', configure.args = '--with-proj-lib=/usr/local/lib/')"; fi;

r_packages:
  - sf
