# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required

addons:
  homebrew:
    packages:
    - pkg-config
    - gdal

r_packages:
  - sf
