# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install pkg-config || echo "fail 1"; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install gdal || echo "fail 2"; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then Rscript -e "install.packages('sf', configure.args = '--with-proj-lib=/usr/local/lib/')"; fi;

r_packages:
  - sf
